export const defaultHomepage = {
  logoType: 'text' as 'text' | 'image',
  logoText: 'IKRAM',
  logoUrl: '',
  navCta: "Let's Talk",
  navCtaLink: '#contact',
  siteTitle: 'Ikram Ullah Khan | Video Editor & Motion Designer',
  heroTag: 'Available for freelance projects',
  heroNameLine1: 'Ikram Ullah',
  heroNameLine2: 'Khan.',
  heroDescription:
    'Video Editor & Motion Designer creating cinematic videos, engaging social content, motion graphics and AI-powered visual stories.',
  heroPrimaryCta: 'View My Work ->',
  heroPrimaryCtaLink: '#work',
  heroSecondaryCta: "Let's Work Together",
  heroSecondaryCtaLink: '#contact',
  heroStats: [
    { value: '1.5+', label: 'Years Experience' },
    { value: '4+', label: 'Creative Services' },
    { value: '100%', label: 'Creative Focus' },
  ],
  workLabel: 'Selected Work',
  workTitle: 'My Portfolio.',
  workDescription: 'A selection of my latest video projects and short-form content.',
  reelsLabel: 'Short Form',
  reelsTitle: 'Reels.',
  reelsDescription: 'Short-form edits made for social media.',
  servicesLabel: 'What I Do',
  servicesTitle: 'Creative services.',
  servicesDescription:
    'From raw footage to polished final videos, I handle the complete visual production process.',
  services: [
    {
      icon: '✦',
      title: 'Video Editing',
      description: 'Professional editing focused on storytelling, pacing and visual impact.',
      imageUrl: '',
      link: '',
      linkLabel: '',
      features: [
        { item: 'Documentary' },
        { item: 'YouTube Videos' },
        { item: 'Corporate Videos' },
        { item: 'Story Videos' },
      ],
    },
    {
      icon: '◈',
      title: 'Motion Design',
      description: 'Dynamic motion graphics that make content visually memorable.',
      imageUrl: '',
      link: '',
      linkLabel: '',
      features: [
        { item: 'Kinetic Typography' },
        { item: 'Logo Animation' },
        { item: 'Explainer Animation' },
        { item: 'UI Animation' },
      ],
    },
    {
      icon: '↗',
      title: 'Social Content',
      description: 'High-retention short-form content optimized for modern platforms.',
      imageUrl: '',
      link: '',
      linkLabel: '',
      features: [
        { item: 'Instagram Reels' },
        { item: 'YouTube Shorts' },
        { item: 'TikTok Videos' },
        { item: 'Promotional Reels' },
      ],
    },
    {
      icon: '✧',
      title: 'AI Visuals',
      description: 'Creative AI-powered visuals for unique storytelling and campaigns.',
      imageUrl: '',
      link: '',
      linkLabel: '',
      features: [
        { item: 'AI Characters' },
        { item: 'AI Scenes' },
        { item: 'AI Drama' },
        { item: 'Image-to-Video' },
      ],
    },
  ],
  aboutLabel: 'About Me',
  aboutTitle: 'Behind every good video is a good story.',
  aboutParagraph1:
    "I'm Ikram Ullah Khan, a Video Editor and Motion Designer focused on creating engaging, cinematic and modern visual content.",
  aboutParagraph2:
    'I combine editing, motion graphics, sound, typography and AI visuals to transform ideas into content that looks professional and keeps viewers engaged.',
  aboutCardLabel: 'VIDEO EDITOR / MOTION DESIGNER',
  aboutCardText: 'Turning ideas into visual stories.',
  aboutList: [
    { item: 'Creative storytelling' },
    { item: 'Cinematic editing' },
    { item: 'Motion graphics' },
    { item: 'Social media content' },
    { item: 'AI visual production' },
    { item: 'Attention to detail' },
  ],
  toolsLabel: 'My Toolkit',
  toolsTitle: 'Software & Tools',
  toolsDescription:
    'The creative tools I use to edit, design, animate and produce visual content.',
  tools: [
    { name: 'Adobe Premiere Pro' },
    { name: 'Adobe After Effects' },
    { name: 'Adobe Photoshop' },
    { name: 'Adobe Illustrator' },
    { name: 'CapCut' },
    { name: 'Mister Horse' },
    { name: 'AI Visual Tools' },
    { name: 'Motion Graphics' },
  ],
  processLabel: 'My Process',
  processTitle: 'From idea to final cut.',
  processDescription:
    'A simple creative workflow designed to keep projects organized and visually strong.',
  processSteps: [
    {
      number: '01 / DISCOVER',
      title: 'Understand',
      description: 'Understand the idea, audience, message and visual direction.',
    },
    {
      number: '02 / CREATE',
      title: 'Edit',
      description: 'Build the story through editing, pacing, music and visual structure.',
    },
    {
      number: '03 / DESIGN',
      title: 'Enhance',
      description: 'Add motion graphics, typography, effects, sound design and AI visuals.',
    },
    {
      number: '04 / DELIVER',
      title: 'Polish',
      description: 'Final color, audio and quality checks before delivering the finished video.',
    },
  ],
  contactLabel: 'Have a Project?',
  contactTitle: "Let's create something",
  contactTitleAccent: 'great together.',
  contactDescription: 'Have an idea, project or video that needs a professional touch?',
  contactEmail: 'ikram@example.com',
  contactCta: 'Start a Conversation ->',
  contactCtaLink: 'mailto:ikram@example.com',
  footerText: '© 2026 Ikram Ullah Khan. All rights reserved.',
  socials: [
    { label: 'Instagram', url: 'https://instagram.com/' },
    { label: 'LinkedIn', url: 'https://linkedin.com/' },
    { label: 'YouTube', url: 'https://youtube.com/' },
  ],
}

export const defaultProjects = [
  {
    title: 'Featured Project',
    category: 'FEATURED PROJECT 01',
    videoUrl: '',
    imageUrl: '',
    link: '',
    linkLabel: 'View Project',
  },
  {
    title: 'Featured Project',
    category: 'FEATURED PROJECT 02',
    videoUrl: '',
    imageUrl: '',
    link: '',
    linkLabel: 'View Project',
  },
  {
    title: 'Featured Project',
    category: 'FEATURED PROJECT 03',
    videoUrl: '',
    imageUrl: '',
    link: '',
    linkLabel: 'View Project',
  },
]

export const defaultReels = [
  { label: 'REEL 01', videoUrl: '/videos/reel-01.mp4', imageUrl: '', link: '' },
  { label: 'REEL 02', videoUrl: '/videos/reel-02.mp4', imageUrl: '', link: '' },
  { label: 'REEL 03', videoUrl: '/videos/reel-03.mp4', imageUrl: '', link: '' },
  { label: 'REEL 04', videoUrl: '/videos/reel-04.mp4', imageUrl: '', link: '' },
  { label: 'REEL 05', videoUrl: '/videos/reel-05.mp4', imageUrl: '', link: '' },
  { label: 'REEL 06', videoUrl: '/videos/reel-06.mp4', imageUrl: '', link: '' },
  { label: 'REEL 07', videoUrl: '/videos/reel-07.mp4', imageUrl: '', link: '' },
  { label: 'REEL 08', videoUrl: '/videos/reel-08.mp4', imageUrl: '', link: '' },
]
