/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    reels: Reel;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    reels: ReelsSelect<false> | ReelsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Optional. Agar nahi pata to Image hi rehne do.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Naya project: Create New → title, cover photo, video, link — sab ek hi form pe. Save dabao.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Jaise: FEATURED PROJECT 01
   */
  category: string;
  /**
   * Website pe thumbnail. Yahi se upload karo.
   */
  coverImage?: (number | null) | Media;
  /**
   * Video yahi se upload. Agar sirf photo + link hai to video skip kar sakte ho.
   */
  video?: (number | null) | Media;
  /**
   * YouTube, Behance, Instagram, ya koi website. Example: https://...
   */
  link?: string | null;
  /**
   * Sirf tab dikhega jab upar link diya ho.
   */
  linkLabel?: string | null;
  /**
   * Chhota number pehle. 1, 2, 3...
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Short videos. Create New → naam + video upload — ek hi page. Save dabao.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels".
 */
export interface Reel {
  id: number;
  label: string;
  /**
   * Thumbnail. Video ke saath bhi laga sakte ho.
   */
  coverImage?: (number | null) | Media;
  /**
   * Yahi se upload. Alag Media page nahi.
   */
  video?: (number | null) | Media;
  /**
   * Instagram / YouTube Shorts link. Example: https://...
   */
  link?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'reels';
        value: number | Reel;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  coverImage?: T;
  video?: T;
  link?: T;
  linkLabel?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels_select".
 */
export interface ReelsSelect<T extends boolean = true> {
  label?: T;
  coverImage?: T;
  video?: T;
  link?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Logo, text, services, about, contact — sab yahan se edit hota hai. Save dabao, website update ho jayegi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Ek choose karo. Baad mein change kar sakte ho.
   */
  logoType?: ('text' | 'image') | null;
  /**
   * Navbar pe yeh naam dikhega.
   */
  logoText?: string | null;
  /**
   * PNG (transparent) best hai. Yahi se upload karo — Media page pe jaane ki zaroorat nahi.
   */
  logoImage?: (number | null) | Media;
  navCta: string;
  /**
   * Examples: #contact  |  mailto:you@email.com  |  https://wa.me/92...  |  https://instagram.com/...
   */
  navCtaLink?: string | null;
  siteTitle: string;
  heroTag?: string | null;
  heroNameLine1?: string | null;
  heroNameLine2?: string | null;
  heroDescription?: string | null;
  heroPrimaryCta?: string | null;
  /**
   * #work, #contact, mailto:, WhatsApp, ya koi website.
   */
  heroPrimaryCtaLink?: string | null;
  heroSecondaryCta?: string | null;
  heroSecondaryCtaLink?: string | null;
  heroStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  workLabel?: string | null;
  workTitle?: string | null;
  workDescription?: string | null;
  reelsLabel?: string | null;
  reelsTitle?: string | null;
  reelsDescription?: string | null;
  servicesLabel?: string | null;
  servicesTitle?: string | null;
  servicesDescription?: string | null;
  /**
   * Add / edit / delete. Har service pe photo aur link laga sakte ho. Sab isi page pe.
   */
  services?:
    | {
        icon?: string | null;
        title: string;
        description: string;
        /**
         * Yahi se upload. Alag page nahi.
         */
        image?: (number | null) | Media;
        /**
         * Click pe kahan jaye? Example: #work  |  https://...  |  mailto:...
         */
        link?: string | null;
        /**
         * Sirf tab dikhega jab link diya ho.
         */
        linkLabel?: string | null;
        features?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  aboutLabel?: string | null;
  aboutTitle?: string | null;
  aboutParagraph1?: string | null;
  aboutParagraph2?: string | null;
  aboutCardLabel?: string | null;
  aboutCardText?: string | null;
  aboutList?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  toolsLabel?: string | null;
  toolsTitle?: string | null;
  toolsDescription?: string | null;
  tools?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  processLabel?: string | null;
  processTitle?: string | null;
  processDescription?: string | null;
  processSteps?:
    | {
        number: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  contactLabel?: string | null;
  contactTitle?: string | null;
  contactTitleAccent?: string | null;
  contactDescription?: string | null;
  contactEmail?: string | null;
  contactCta?: string | null;
  /**
   * mailto:email  |  WhatsApp link  |  koi URL. Khali chhodo to Contact Email use hogi.
   */
  contactCtaLink?: string | null;
  footerText?: string | null;
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  logoType?: T;
  logoText?: T;
  logoImage?: T;
  navCta?: T;
  navCtaLink?: T;
  siteTitle?: T;
  heroTag?: T;
  heroNameLine1?: T;
  heroNameLine2?: T;
  heroDescription?: T;
  heroPrimaryCta?: T;
  heroPrimaryCtaLink?: T;
  heroSecondaryCta?: T;
  heroSecondaryCtaLink?: T;
  heroStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  workLabel?: T;
  workTitle?: T;
  workDescription?: T;
  reelsLabel?: T;
  reelsTitle?: T;
  reelsDescription?: T;
  servicesLabel?: T;
  servicesTitle?: T;
  servicesDescription?: T;
  services?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        image?: T;
        link?: T;
        linkLabel?: T;
        features?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  aboutLabel?: T;
  aboutTitle?: T;
  aboutParagraph1?: T;
  aboutParagraph2?: T;
  aboutCardLabel?: T;
  aboutCardText?: T;
  aboutList?:
    | T
    | {
        item?: T;
        id?: T;
      };
  toolsLabel?: T;
  toolsTitle?: T;
  toolsDescription?: T;
  tools?:
    | T
    | {
        name?: T;
        id?: T;
      };
  processLabel?: T;
  processTitle?: T;
  processDescription?: T;
  processSteps?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  contactLabel?: T;
  contactTitle?: T;
  contactTitleAccent?: T;
  contactDescription?: T;
  contactEmail?: T;
  contactCta?: T;
  contactCtaLink?: T;
  footerText?: T;
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}